pipeline {
    agent any

    environment {
        MAVEN_HOME = tool 'Maven-3.9.0' // Ensure this matches your Maven tool name
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub repository
                git url: 'https://github.com/Shreyad01/jenkinsPractice', branch: 'master', credentialsId: '727edad4-c383-4574-a868-9570224b1bc0'
            }
        }

        stage('Build') {
            steps {
                // Build the project using Maven
                script {
                    withEnv(["PATH+MAVEN=${MAVEN_HOME}\\bin"]) {
                        sh "echo $PATH"
                        sh 'mvn clean install'
                    }
                }
            }
        }

        stage('Test') {
            // Run tests using Maven
           steps {
                script {
                   withEnv(["PATH+MAVEN=${MAVEN_HOME}\\bin"]) {
                        sh 'mvn test'
                    }
                }
               }   
        }


        stage('Archive Artifacts') {
            steps {
                // Archive the built artifacts
                archiveArtifacts artifacts: 'target/*.war', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
        success {
            echo 'Pipeline succeeded.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
